name: Tests

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * * '
  repository_dispatch:
    types:
      - test


jobs:
  # Build and unit test
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: execute action
      uses: ./.github/actions/cache-test
