name: Tests

on:
  push:
    branches:
      - master

jobs:
  # Build and unit test
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: execute action
      uses: ./.github/actions/cache-test
